## NumPy

## Numpy Arrays

In [1]:
import numpy as np

### Creating NumPy Arrays from a Python List

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in Methods to generate Arrays

#### arange

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

#### zeros and ones

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

np.ones((3,3))

#### linspace

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

#### eye

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random 

#### rand

In [17]:
np.random.rand(2)

array([0.40072857, 0.01911872])

In [18]:
np.random.rand(5,5)

array([[0.9818536 , 0.9714156 , 0.97398372, 0.64059598, 0.63078983],
       [0.936391  , 0.95935559, 0.96016473, 0.62734216, 0.20560614],
       [0.5117141 , 0.50787737, 0.68219809, 0.47653373, 0.84517898],
       [0.13809791, 0.67368497, 0.92156529, 0.67909305, 0.62863603],
       [0.09534934, 0.27923618, 0.24467118, 0.60538046, 0.06897003]])

#### randn

In [20]:
np.random.randn(2)

array([-0.31935503, -0.62282204])

In [21]:
np.random.randn(5,5)

array([[-0.94356228,  0.05091053,  1.14898074,  0.23223289, -0.63809053],
       [ 0.52397606,  0.21246707, -0.23148442, -0.57578126, -0.46569856],
       [ 0.3880215 ,  0.82397593,  2.0959448 , -0.02048513,  0.2599708 ],
       [ 0.35477106, -1.02855489, -2.73296199,  0.49450713,  1.08587962],
       [-1.16653186,  0.64286132, -1.65705494,  0.32509819, -0.28471715]])

##### randint

In [22]:
np.random.randint(1,100)

26

In [23]:
np.random.randint(1,100,10)

array([ 5, 53,  2, 11, 95, 20, 84, 40, 48, 38])

### Array Attributes and Methods

In [24]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr

array([ 7, 14, 23,  1,  8, 34, 15, 42, 40, 44])

### Reshape

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### max,min,argmax,argmin

In [30]:
ranarr

array([ 7, 14, 23,  1,  8, 34, 15, 42, 40, 44])

In [31]:
ranarr.max()

44

In [32]:
ranarr.argmax()

9

In [35]:
ranarr.min()

1

In [34]:
ranarr.argmin()

3

### Shape

In [36]:
arr.shape

(25,)

In [37]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [38]:
arr.reshape(1,25).shape

(1, 25)

In [39]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [40]:
arr.reshape(25,1).shape

(25, 1)

### dtype

In [41]:
arr.dtype

dtype('int32')